[package]
name = "rust-cid"
version = "0.1.0"
authors = ["Aten <jincxmain@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0"
integer-encoding = "1.0"

multihash = { package = "parity-multihash", version = "0.2" }
multibase = { package = "rust-multibase", path = "../multibase" }
