[workspace]
members = [
    "core/amt-ipld",
    "core/block-format",
    "core/cid",
    "core/hamt-ipld",
    "core/hamt-ipld2",
    "core/ipfs/blockstore",
    "core/ipld/cbor",
    "core/ipld/format",
    "core/multibase",
    "core/util",
]
