[workspace]
members = [
    "core/multibase",
    "core/cid",
    "core/primitives",
    "core/ipld/cbor",
    "core/ipld/format",
    "core/block-format",
    "core/hamp-ipld",
    "core/util",
    "core/merkledag",
]
