[workspace]
members = [
    "core/amt-ipld",
    "core/block-format",
    "core/cid",
    "core/datastore",
    "core/ds/rocksdb",
    "core/hamt-ipld",
    "core/hamt-ipld2",
    "core/ipfs/blockstore",
    "core/ipld/cbor",
    "core/ipld/format",
    "core/multibase",
    "core/util",
    "paritylibs/kvdb",
    "paritylibs/kvdb-rocksdb",
]
