[package]
name = "rust-ipld-cbor"
version = "0.1.0"
authors = ["Aten <jincxmain@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
bytes = { version = "0.5", features = ["serde"] }

serde_cbor = { git = "https://github.com/PolkaX/cbor", branch = "impl-tag" }

ipld-format = { package = "rust-ipld-format", path = "../format" }
block-format = { package = "rust-block-format", path = "../../block-format" }
cid = { package = "rust-cid", path = "../../cid" }