[package]
name = "cid-ext"
version = "0.1.0"
authors = ["PolkaX <https://github.com/PolkaX>"]
edition = "2018"

[dependencies]
cid = { version = "0.4", features = ["impl-serde"] }

[features]
nightly = []