[package]
name = "rust-block-format"
version = "0.1.0"
authors = ["Aten <jincxmain@gmail.com>"]
edition = "2018"

[dependencies]
thiserror = "1.0"
bytes = { version = "0.5", features = ["serde"] }

rust-cid = { path = "../cid" }
ipfs-util = { package = "rust-ipfs-util", path = "../util" }

[dev-dependencies]
multihash = { package = "parity-multihash", version = "0.2" }
