[package]
name = "rust-block-format"
version = "0.1.0"
authors = ["Aten <jincxmain@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"

multihash = "0.8.0"

# local crate
primitives = { path = "../primitives" }
rust-cid = { path = "../cid" }

ipfs-util = { package = "rust-ipfs-util", path = "../util" }
