[package]
name = "primitives"
version = "0.1.0"
authors = ["PolkaX <https://github.com/PolkaX>"]
edition = "2018"

license = "MIT/Apache-2.0"
repository = "https://github.com/PolkaX/rust-ipfs"
description = "Some primitives of rust-ipfs"
keywords = ["ipfs", "primitives"]

[dependencies]
