[package]
name = "merkledag"
version = "0.1.0"
authors = ["Aten <jincxmain@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipld-format = { package = "rust-ipld-format", path = "../ipld/format" }