[package]
name = "merkledag"
version = "0.1.0"
authors = ["PolkaX <https://github.com/PolkaX>"]
edition = "2018"

license = "MIT/Apache-2.0"
repository = "https://github.com/PolkaX/rust-ipfs"
description = "Implementation of the merkledag"
keywords = ["ipfs", "merkledag"]

[dependencies]
