on: [push, pull_request]

name: build

jobs:
  build:
    name: Lint and Test
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        toolchain: [nightly-2019-12-20]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Run cargo test with all features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
